# Generated by Django 2.0.2 on 2018-02-25 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserUpdateEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_time', models.DateTimeField(auto_now_add=True)),
                ('snapshot', models.TextField()),
                ('publisher', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='event_publisher', related_query_name='publisher', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
