# Generated by Django 2.0.2 on 2018-02-25 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('updater', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userupdateevent',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='event_publisher', related_query_name='publisher', to=settings.AUTH_USER_MODEL),
        ),
    ]
