# Generated by Django 2.0.2 on 2018-02-22 16:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailer', '0002_auto_20180221_0753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailactivity',
            name='last_email',
            field=models.DateField(default=datetime.date(2018, 2, 22)),
        ),
    ]
