# Generated by Django 2.0.2 on 2018-02-22 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailer', '0003_auto_20180222_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailactivity',
            name='last_email',
            field=models.DateField(auto_now_add=True),
        ),
    ]
