# Generated by Django 2.0.2 on 2018-02-24 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emailer', '0005_auto_20180222_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_time', models.DateTimeField(auto_now_add=True)),
                ('publisher', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='event_publisher', related_query_name='publisher', to='emailer.EmailActivity')),
            ],
        ),
    ]
